### ISSUE TITLE
Pocketmine 4 Support?

### ISSUE THREAD

**Issue by PocketMiner92** [TheBalkanDev/MobPlugin-PM#6]
Is this Plugin ready for Pocketmine 4?

**Comment by TheBalkanDev** [comment]
Dear @PocketMiner92,

This Project was canceled.

The Reasons were that I quitted PHP coding, because I need to put more time in my C# and Java Projects.

i don’t recommend using Pocketmine anymore.
Use Spigot and install the Geyser and Flootgate Plugin and now you can play with MCBE/ Win10 Edition as well.

This repository will be used for something grest!
Kind regards.

**Comment by PocketMiner92** [comment]
Geyser?
No thanks, its too Buggy.
